# Generated by Django 3.2.12 on 2024-04-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20240421_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ImageField(blank=True, default='the_thinker.png', upload_to=''),
        ),
    ]
