# Generated by Django 3.2.12 on 2024-03-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='permalink',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
