# Generated by Django 3.2.12 on 2024-04-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240405_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='number',
            field=models.IntegerField(default=8),
        ),
    ]
