# Generated by Django 3.2.12 on 2024-04-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pic',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.IntegerField(default=9, verbose_name='Magic Number'),
        ),
    ]
