# Generated by Django 3.2.12 on 2024-04-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.IntegerField(default=7, verbose_name='Magic Number'),
        ),
    ]
